networks:
  pixelcast_network:
    driver: bridge
  cloudflare_network:
    external: true

services:
  # SRS Streaming Server
  srs:
    image: ossrs/srs:6
    container_name: pixelcast-srs
    restart: unless-stopped
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf:ro
      - srs_data:/usr/local/srs/objs/nginx/html
      - srs_logs:/usr/local/srs/objs
    ports:
      - "1935:1935" # RTMP
      - "1985:1985" # HTTP API
      - "8080:8080" # HTTP Server (for demos/players)
      - "8000:8000/udp" # WebRTC over UDP
      - "8001:8001/tcp" # WebRTC over TCP (Fallback)
    environment:
      - CANDIDATE=srs
    networks:
      - pixelcast_network
      - cloudflare_network

  # Backend Service
  pixelcast-api:
    image: lst97/pixel-cast-backend:latest
    container_name: pixelcast-backend
    restart: unless-stopped
    ports:
      - "3011:3001"
    volumes:
      - backend_data:/app/data
    depends_on:
      - srs
    environment:
      - SRS_SERVER_IP=srs
      - SRS_HTTP_API_URL=http://srs:1985
      - SRS_RTMP_URL=rtmp://srs:1935
      - SRS_HLS_URL=http://srs:8080
      - BACKEND_PORT=3001
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - pixelcast_network
      - cloudflare_network

  # Frontend Service
  pixelcast:
    image: lst97/pixel-cast-frontend:latest
    container_name: pixelcast-frontend
    restart: unless-stopped
    ports:
      - "3010:3000"
    depends_on:
      - pixelcast-api
      - srs
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
      - NEXT_PUBLIC_SRS_HTTP_API_URL=http://srs:1985
      - NEXT_PUBLIC_SRS_RTMP_URL=rtmp://srs:1935
      - NEXT_PUBLIC_SRS_HLS_URL=http://srs:8080
      - NEXT_PUBLIC_SRS_WEBRTC_URL=http://srs:8000
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - pixelcast_network
      - cloudflare_network

volumes:
  srs_data:
    driver: local
  srs_logs:
    driver: local
  backend_data:
    driver: local
